server:
  port: 8800

spring:
  application:
    name: config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
test: ConfigClient-dev-2.0

management:
  security:
    enabled: false
